include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat all lints as info (don't fail CI)
    invalid_assignment: ignore
    missing_required_argument: ignore
    missing_return: ignore
    todo: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_locals: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    curly_braces_in_flow_control_structures: ignore
    file_names: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_const_declarations: ignore
    sort_pub_dependencies: ignore
    unnecessary_const: ignore
    avoid_init_to_null: ignore
    use_super_parameters: ignore
    avoid_relative_lib_imports: ignore
    use_key_in_widget_constructors: ignore
    prefer_interpolation_to_compose_strings: ignore
    unnecessary_lambdas: ignore
