#!/usr/bin/env bash
# cloudflared-setup.sh — Optional post-install step for M-NEXUS.
#
# Sets up a Cloudflare Tunnel that:
#   - Exposes M-NEXUS backend (port 4100) at a subdomain (e.g. notes.example.com)
#   - Hides your origin IP (only Cloudflare sees it)
#   - Provides free DDoS protection + bot filtering upstream
#   - Optionally 2FA via Cloudflare Access (configured separately in dashboard)
#
# Requirements:
#   - A Cloudflare account (free)
#   - A domain added to Cloudflare DNS (free tier is fine)
#   - This script must run as a user with sudo (for installing cloudflared + service)
#
# After running:
#   1. Open https://notes.example.com in your browser
#   2. To enable 2FA: visit https://one.dash.cloudflare.com → Access → Applications

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────
PORT="${MNEXUS_PORT:-4100}"
TUNNEL_NAME="${MNEXUS_TUNNEL_NAME:-mnexus}"
HOSTNAME="${MNEXUS_HOSTNAME:-}"

# ── Helpers ────────────────────────────────────────────────────────────
ask() {
  local prompt="$1"
  local default="${2:-}"
  local reply
  if [ -n "$default" ]; then
    read -rp "$prompt [$default]: " reply
    reply="${reply:-$default}"
  else
    read -rp "$prompt: " reply
  fi
  echo "$reply"
}

detect_os() {
  case "$(uname -s)" in
    Linux)  echo "linux" ;;
    Darwin) echo "macos" ;;
    MINGW*|CYGWIN*|MSYS*) echo "windows" ;;
    *) echo "unsupported: $(uname -s)" >&2; exit 1 ;;
  esac
}

# ── 1. Install cloudflared ─────────────────────────────────────────────
install_cloudflared() {
  if command -v cloudflared >/dev/null 2>&1; then
    echo "✓ cloudflared already installed: $(cloudflared --version 2>&1 | head -1)"
    return
  fi
  echo "→ Installing cloudflared..."
  local os
  os=$(detect_os)
  case "$os" in
    linux)
      local arch
      arch=$(uname -m)
      case "$arch" in
        x86_64) arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *) echo "Unsupported arch: $arch" >&2; exit 1 ;;
      esac
      local deb="cloudflared-linux-${arch}.deb"
      curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/$deb" -o "/tmp/$deb"
      sudo dpkg -i "/tmp/$deb"
      rm "/tmp/$deb"
      ;;
    macos)
      if command -v brew >/dev/null 2>&1; then
        brew install cloudflared
      else
        echo "Install Homebrew first: https://brew.sh" >&2
        exit 1
      fi
      ;;
    windows)
      winget install Cloudflare.cloudflared
      ;;
  esac
  echo "✓ cloudflared installed"
}

# ── 2. Login ───────────────────────────────────────────────────────────
login_cloudflare() {
  if [ -f "$HOME/.cloudflared/cert.pem" ]; then
    echo "✓ Already logged in to Cloudflare (cert.pem found)"
    return
  fi
  echo "→ Opening browser for Cloudflare login..."
  cloudflared tunnel login
  echo "✓ Logged in"
}

# ── 3. Create tunnel ───────────────────────────────────────────────────
create_tunnel() {
  if cloudflared tunnel info "$TUNNEL_NAME" >/dev/null 2>&1; then
    echo "✓ Tunnel '$TUNNEL_NAME' already exists"
    return
  fi
  echo "→ Creating tunnel '$TUNNEL_NAME'..."
  cloudflared tunnel create "$TUNNEL_NAME"
  echo "✓ Tunnel created"
}

# ── 4. Configure ───────────────────────────────────────────────────────
write_config() {
  mkdir -p "$HOME/.cloudflared"
  local cred_file="$HOME/.cloudflared/${TUNNEL_NAME}.json"
  [ ! -f "$cred_file" ] && [ -f "$HOME/.cloudflared/cert.pem" ] && {
    # Pick the most recent .json in the dir
    cred_file=$(ls -t "$HOME"/.cloudflared/*.json 2>/dev/null | head -1)
  }
  cat > "$HOME/.cloudflared/config.yml" <<EOF
# M-NEXUS Cloudflare Tunnel config
# Generated by scripts/cloudflared-setup.sh

tunnel: $TUNNEL_NAME
credentials-file: $cred_file

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:$PORT
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      keepAliveConnections: 4
  - service: http_status:404
EOF
  echo "✓ Config written to $HOME/.cloudflared/config.yml"
}

# ── 5. DNS route ───────────────────────────────────────────────────────
route_dns() {
  if [ -z "$HOSTNAME" ]; then
    echo "⚠ No hostname set; skipping DNS route. You'll need to add it manually in Cloudflare dashboard:"
    echo "    Type: CNAME  Name: $TUNNEL_NAME  Target: $(cloudflared tunnel info $TUNNEL_NAME | grep -oP '[a-f0-9-]+\.cfargotunnel\.com')"
    return
  fi
  echo "→ Adding DNS route for $HOSTNAME..."
  cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"
  echo "✓ DNS route added"
}

# ── 6. Install as service ──────────────────────────────────────────────
install_service() {
  local os
  os=$(detect_os)
  echo "→ Installing cloudflared as system service..."
  case "$os" in
    linux)
      sudo cloudflared service install
      sudo systemctl enable cloudflared
      sudo systemctl restart cloudflared
      echo "✓ Systemd service installed and started"
      echo "  Logs: sudo journalctl -u cloudflared -f"
      ;;
    macos)
      cloudflared service install
      echo "✓ launchd service installed"
      echo "  Logs: tail -f /usr/local/var/log/cloudflared.log"
      ;;
    windows)
      echo "Run 'cloudflared service install' from an Administrator cmd."
      ;;
  esac
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
  echo
  echo "🚇 M-NEXUS Cloudflare Tunnel Setup"
  echo
  HOSTNAME="${HOSTNAME:-$(ask "Subdomain for M-NEXUS (e.g. notes.example.com)")}"
  if [ -z "$HOSTNAME" ]; then
    echo "Hostname is required." >&2
    exit 1
  fi
  TUNNEL_NAME="${TUNNEL_NAME:-$(ask "Tunnel name" "mnexus")}"

  install_cloudflared
  login_cloudflare
  create_tunnel
  write_config
  route_dns
  install_service

  echo
  echo "═══════════════════════════════════════════════════════════"
  echo "✅ Done! Your M-NEXUS is live at: https://$HOSTNAME"
  echo "═══════════════════════════════════════════════════════════"
  echo
  echo "  Cloudflare handles (free):"
  echo "    • DDoS protection"
  echo "    • Bot filtering"
  echo "    • TLS termination"
  echo "    • Caching"
  echo "    • Rate limiting (in dashboard)"
  echo
  echo "  To enable 2FA (recommended for public deploys):"
  echo "    1. Go to https://one.dash.cloudflare.com/"
  echo "    2. Access → Applications → Add application → Self-hosted"
  echo "    3. Application domain: $HOSTNAME"
  echo "    4. Policy: Allow + Email or One-Time PIN"
  echo
  echo "  M-NEXUS auth still runs at the app level (admin login)."
  echo "  Cloudflare Access adds an extra layer before traffic even reaches you."
}

main "$@"
